echo "Launching Winfinicord (https://winfinicord.net)"
echo "Checking for commits to the repository"
echo "Updating"
echo "Connecting to websocket"
echo "Launched!"
xdg-open "https://scratch.mit.edu/projects/410483221/"
